# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='objStore',
            fields=[
                ('uniqueID', models.AutoField(primary_key=True, serialize=False)),
                ('userIP', models.GenericIPAddressField()),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('objText', models.TextField()),
            ],
        ),
    ]
